### ISSUE TITLE
reference genome path

### ISSUE THREAD

**Issue by gneedle1** [AmpliconSuite/AmpliconSuite-pipeline#21]
Hi! When I run prepareAA it can't find mt reference genome (GRCh38.tar). The first error I got was:
 Traceback (most recent call last):
  File "PrepareAA.py", line 505, in <module>
    ref = gdir + refFnames[args.ref]
TypeError: can only concatenate str (not "NoneType") to str

 So I changed the refFnames array, but now I get:
Traceback (most recent call last):
  File "PrepareAA.py", line 14, in <module>
    import check_reference
  File "/home/gabe/PrepareAA/check_reference.py", line 12
    def get_ref_fname(aa_dr_path, rname):    with open(aa_dr_path + "/" + rname + "/file_list.txt") as infile:

Traceback (most recent call last):
  File "PrepareAA.py", line 480, in <module>
    refFnames[rname] = check_reference.get_ref_fname(AA_REPO, rname)
  File "/home/gabe/PrepareAA/check_reference.py", line 13, in get_ref_fname
    with open(aa_dr_path + "/" + rname + "/file_list.txt") as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gabe/AmpliconArchitect/data_repo//GRCh38/file_list.txt'

It seems like I should name my file differently but I am not sure. Thoughts? Thank you!

**Comment by jluebeck** [comment]
Hi, can you confirm that you have downloaded the data repo? If you list do `ls $AA_DATA_REPO/GRCh38`, do you see anything present? You can obtain it from https://datasets.genepattern.org/?prefix=data/module_support_files/AmpliconArchitect/

There are versions containing both the bwa indexed (GRCh38_indexed.tar.gz) and smaller unindexed (GRCh38.tar.gz) forms.

Please let me know if you have any questions or issues persist.

Thanks,
Jens
