### ISSUE TITLE
Directory issue

### ISSUE THREAD

**Issue by uretaj** [AmpliconSuite/AmpliconSuite-pipeline#40]
Hi,

I'm running multiple samples in parallel but  since the file paa_envs.txt is the same filename for all samples and it's getting written in the home folder instead of the output folder, it is causing the sample name to be overwritten and different from the time of creation of the output directory and processing of sample.

**Comment by jluebeck** [comment]
Hi, thanks for pointing this out. I just pushed a change to the unstable_dev branch to resolve this. You are welcome to test it out and let me know if it works for you, otherwise I will test sometime early next week and bring it into the main branch then.

Thanks,
Jens

**Comment by uretaj** [comment]
Hi,

Will it also be an issue that they are sharing the file paa_singularity.sh?

**Comment by jluebeck** [comment]
Yes, good point - I have just pushed a fix for this issue (both singularity and docker) to the [unstable_dev](https://github.com/AmpliconSuite/AmpliconSuite-pipeline/tree/unstable_dev) branch. I am planning to do a bit more development and testing on other things so these changes probably won't be in the main branch until sometime next week but you are welcome to download the updated runscripts from the unstable_dev branch and try them out with the existing container image you have in the meantime.

**Comment by jluebeck** [comment]
Thank you for catching that - just pushed the fix to unstable_dev!

Jens

**Comment by jluebeck** [comment]
Fixed in 597e173d5c395a7f8c5f70817f431d21e8ac8160 (0.1555.1 and later)
