### ISSUE TITLE
Support for non-human species

### ISSUE THREAD

**Issue by Chao-Guo-hub** [AmpliconSuite/AmpliconSuite-pipeline#45]
In addition to humans and mice, we are concerned about the presence of ecDNA in other species, so will there be an update for custom reference genome databases in a later version?

**Comment by jluebeck** [comment]
Sorry, there are no plans to add support for additional species at this time. Saccharomyces cerevisiae (yeast) or Drosophila melanogaster (fruit fly) are possibilities if we see a significant number of users request them.

**Comment by Chao-Guo-hub** [comment]
Well, that's a shame. I wonder what limits the expansion of the species? Maybe I could build my own database of interesting species with a few code changes?

**Comment by jluebeck** [comment]
Providing additional reference support for species requires us to construct a custom annotation database. Unfortunately that process is quite complicated and requires multiple different annotation files to be available from the UCSC genome browser and from other sites. It also requires us to first collect a sizable panel of "normal" WGS samples from that species to use in generating baseline CNV calls throughout the genome. Unfortunately, not all species are as well-annotated as human and mouse so it may not even be feasible. The AA genome annotations are used for marking low complexity, repetitive regions, low-mappability regions, oncogenes, as well as areas that show high signal across many "normal" samples. Generating such a database takes at minimum a few weeks of dedicated work on our end, without yet factoring in the time it takes to test this new data repo and validate that it works properly (at least another week). Naturally we must be very judicious about which species we are able to support. 

Thanks,
Jens

**Comment by Chao-Guo-hub** [comment]
Thank you very much for your reply!
We mainly focus on some domesticated animals such as pigs, cows, chickens and dogs. If there is an update planned you can reopen the tissue.
