### ISSUE TITLE
Software dependencies in README

### ISSUE THREAD

**Issue by auberginekenobi** [AmpliconSuite/AmpliconSuite-pipeline#5]
Set this up over the weekend and thought I'd list the software dependencies that I required which weren't explicitly mentioned in the readme:
scipy, numpy, python 2, pysam, mosek, matplotlib.
In addition, worth mentioning that PrepareAA currently requires the jluebeck fork of AmpliconArchitect.

**Comment by jluebeck** [comment]
Covered by revised installation instructions/containers/web interfaces
