### ISSUE TITLE
Amplicon Classifier error in grouped analysis mode using mamba installed pipeline

### ISSUE THREAD

**Issue by bweasels** [AmpliconSuite/AmpliconSuite-pipeline#50]
It seems like `compute_f_from_AA_graph` function in the amplicon classifier part of the pipeline might have something up with it as it is consistently throwing the following error: 

```
home/bkw2118/miniforge3/envs/ampsuite/lib/python3.10/site-packages/ampclasslib/amplicon_classifier.py -i /mnt/data/bkw2118/EAC_quant/820979bae_AAOut/B1_1/B1_1_classification/B1_1.input --ref GRCh38 -o /mnt/data/bkw2118/EAC_quant/820979bae_AAOut/B1_1/B1_1_classification/B1_1 --report_complexity
reading /mnt/data/bkw2118/refGenome/data_repo/GRCh38/Genes_hg38.gff
read 22998 genes

B1_1 amplicon100
Traceback (most recent call last):
  File "/home/bkw2118/miniforge3/envs/ampsuite/lib/python3.10/site-packages/ampclasslib/amplicon_classifier.py", line 1149, in <module>
    run_classification(segSeqD, cycleList, cycleCNs)
  File "/home/bkw2118/miniforge3/envs/ampsuite/lib/python3.10/site-packages/ampclasslib/amplicon_classifier.py", line 797, in run_classification
    fb_edges, fb_readcount, fb_prop, maxCN, tot_over_min_cn = compute_f_from_AA_graph(graphFile, args.add_chr_tag)
ValueError: not enough values to unpack (expected 5, got 4)
```
I'm using the mamba version of the pipeline, `(AmpliconSuite-pipeline version 1.2.1)` - please let me know if you need any more info to help figure this out.

**Comment by bweasels** [comment]
Hi Jens,
  Thanks so much for the quick reply! My `$AC_SRC` is `/home/bkw2118/miniforge3/envs/ampsuite/lib/python3.10/site-packages/ampclasslib`. Of note, when I installed the package (on Saturday I believe), the command `source install.sh --finalize_only` from the mamba install instructions set my $AA_SRC and $AC_SRC to `/AmpliconArchitect/ampliconarchitectlib/` and `/AmpliconArchitect/ampclasslib/`, (or something similar... I overwrote it so I forget the exact path) so I had to manually find the scripts that were supposed to be in those folders and set the $AA_SRC and $AC_SRC manually. The AA scripts were in the `...miniforge3/envs/ampsuite/lib/python3.10/site-packages/ampliconarchitectlib/` folder, but the AC scripts were in `...miniforge3/envs/ampsuite/bin`. There are unfortunately no git repos associated with those directories, so I can't pull. Maybe the bioconda or conda-forge is a bit behind the most recent release or something?
  My `amplicon_classifier.py -v` is 1.1.0
  If it would help, I can remove my environment and do a clean install to get the accurate paths of all the files.
Thanks again for the speedy help, and I hope this isn't too much of a bother.
-Ben

**Comment by jluebeck** [comment]
Hi Ben,

Thanks for the info this is really helpful. This bug you encountered exists in AC v1.1.0, but it has been fixed in AC v1.1.1, which is what is packaged with AmpliconSuite-pipeline v1.2.1. Can you perhaps wipe the installation of this package from your system and go with a fresh install?

Jens

**Comment by bweasels** [comment]
Ah I figured it out, and it is a bit embarrassing. I hadn't updated my conda installation since ~2 weeks ago, so it was pulling from an older version of the package instead of the newest one. `amplicon_classifier.py -v` is now returning 1.1.1
Thanks again for helping! I'll restart my batch job and hopefully it all runs smoothly!!
-Ben

**Comment by jluebeck** [comment]
No worries at all! I need to make sure I am not pushing out buggy builds in the future :) 
Cheers,
Jens
