### ISSUE TITLE
interchange between species A and B in data repo

### ISSUE THREAD

**Issue by Shuixin-Li** [AmpliconSuite/AmpliconSuite-pipeline#53]
Thank you for your fab work of this AmpliconSuite-pipeline! I now want to use it of the species of Cavia porcellus. Could you share the steps how to create a data repo of non-human and non-mouse species? 

**If it's barely impossible to create a custom data repo, can I do some interchange** between the Cavia porcellus and mouse data? Would you have some advice? Because the mouse data in the data repo have gene ID, I am thinkig about the possiblity to transit from one species to the other. 

last part of the question: about the file `GenomicSuperDup.tab` . is there only one way that we download this file from somewhere in website rather than create by ourselves? if we can create, could you please kindly teach me how to generate one?

**Comment by jluebeck** [comment]
Hi, I'm, not sure how this would be possible - from what I can tell the Cavia porcellus genome has not been resolved to chromosome level - only contig level on fairly low coverage assembly. 

AA requires well-resolved chromosome assemblies and genome annotations to work. For segmental duplications you could try something like this: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6129265/

Keep in mind that the AA method also requires a database of regions which appear with CN >=4.5 in normal genomes (requires a panel of normal CNV analyses from multiple samples), as well as an ignorefile of problematic parts of that genome (repetitive and low-complexity sequence). I am skeptical that these can be created for organisms without highly-refined genome assemblies and large amounts of public sequencing data (e.g. human, mouse, drosophila, yeast, etc.).

Just to be clear - I also want to mention that the AA tool is for ecDNA detection in cancer, and is not designed for small eccDNA detection in normal genomes.

Thanks,
Jens

**Comment by Shuixin-Li** [comment]
Thank you for your detailed reply Jens. Yes I am going to detect ecDNA in cancer.

I am clear with everything now!

Thank you very much! ;)
