### ISSUE TITLE
Pipeline stalling at plotting SV view

### ISSUE THREAD

**Issue by at10101** [AmpliconSuite/AmpliconSuite-pipeline#60]
Hi,
I am running AmpliconArchitect on WGS data (10x) and it has stalled at "plotting SV view" on a couple of samples without progressing for more than 4 days, but completed within a day for most of the other samples.
Do you know why this might be?
Thanks

[root:INFO] #TIME 4444.386   Detecting breakpoint edges (interval filter vertices)
[root:INFO] #TIME 8978.242   Building breakpoint graph
[root:INFO] #TIME 8987.568   Optimizing graph copy number flow
[MOSEK:INFO]    Beginning MOSEK call
[root:INFO] #TIME 9004.819   Plotting SV View

**Comment by jluebeck** [comment]
Hi, thanks for reaching out about this. This is one of the more common issues reported by users for AA. Typically it will happen with extremely complex focal amplifications. Can you confirm if the CNV seeds were generated using CNVkit or were they provided from an external caller? Are you able to share the complete log file and/or stdout from the run?

Thanks,
Jens

**Comment by jluebeck** [comment]
In the meantime, you may want to try running with `--AA_insert_sdevs 9`, to help remove sequencing artifacts if they are the cause.

Thanks,
Jens

**Comment by at10101** [comment]
Hi Jens, thanks for your help. Yes the CNV seeds were generated using CNVkit. 
Please find attached the log files.

[SAMPLE19_B.command.txt](https://github.com/user-attachments/files/15786517/SAMPLE19_B.command.txt)
[SAMPLE30_C.command.txt](https://github.com/user-attachments/files/15786518/SAMPLE30_C.command.txt)

**Comment by at10101** [comment]
Thanks. Our MultiQC gave properly paired rates of 93% and 88% so not sure why it was much lower with AA pipeline.
Our WGS data is from xenograft so has both mouse and human reads if that has any effect.
We plan to re-run with BAM files as input rather than FASTQ to see if it makes any difference.

**Comment by jluebeck** [comment]
Interesting, this is very helpful. The properly paired rate reported by is
from running samtools flagstat on the provided bam file (or generated bam
file). When fastqs are provided, BWA MEM is called with basically default
parameters. It would be interesting then to know why the two properly
paired rates are so discrepant. It is very possible that unless the
mouse-specific reads are first removed, then the pipeline will not work as
expected.

Thanks,
Jens
