### ISSUE TITLE
Tumor-only vs Normal-paired

### ISSUE THREAD

**Issue by yaosichao0915** [AmpliconSuite/AmpliconSuite-pipeline#63]
I noticed that AA can work with tumor-only WGS data since it was tested on the cell line data. I am just wondering what would be the benefits if giving with paired normal WGS as well.

**Comment by yaosichao0915** [comment]
> Hi, this is a great question. While AA itself will not used the paired normal BAM, the focal amplification seed region detection stage performed by CNVKit will utilize the normal bam and this may help improve quality of CNV calls used for seeding - particularly in reducing false positive amplifications.
> 
> Jens

**Comment by yaosichao0915** [comment]
> Hi, this is a great question. While AA itself will not used the paired normal BAM, the focal amplification seed region detection stage performed by CNVKit will utilize the normal bam and this may help improve quality of CNV calls used for seeding - particularly in reducing false positive amplifications.
> 
> Jens

Thanks Jens. One Further question on this topic, since you mentioned false positive amplifications. Is there any tips to figure out the false positive? like low copy number or not on coding genes or through the amplicon picture provided?

**Comment by jluebeck** [comment]
If you see the same exact event in multiple unrelated samples, this can be an indicator of a false positive (similarity score reported by AmpliconClassifier may help establish this). Events with highly uneven CN number in low-complexity regions of the genome are definitely suspect amplicons - you may see something like this in the AA sashimi plots. We have otherwise put a large amount of work into building a database AA uses to filter problematic parts of the genome, so the false-positive rate should be low already.

**Comment by newpest** [comment]
Hi Jens, I have a small question. We found that the Amplicons obtained when using different Caller seeds as input will be very different. For example, when using ReadDepth and Cnvkit, there will be many different Amplicons with low average copy ratios. Should these Amplicons be ignored?

**Comment by jluebeck** [comment]
Yes, the caller used for seed identification can influence the results. ReadDepth is now deprecated and we recommend CNVkit for the seed identification stage. I would be happy to take a look and provide feedback on some of these discrepant results if you would like to share. I would imagine most of these are falling into the "linear" class.

**Comment by jluebeck** [comment]
Hi - 

I have not tried Sequenza so unfortunately I cannot comment on how it may compare. Please feel free to try and let me know how it goes.

Keep in mind - the CNV calls passed to AmpliconSuite are used only for identification of seed regions where focal amps may exist. After the seed regions are identified CNV is completely and independently re-called by AmpliconArchitect. CNVkit has been a good choice for seed identification as it identifies and segments these high CN areas without undersegmenting like some callers are prone to. It also does not force things into integer CN states either.

Jens
